
import React, { useState } from 'react';
import { Icons } from './Icons';
import { SurveyData } from '../types';
import { GOOGLE_FORM_BASE_URL } from '../constants';

interface SurveyFormProps {
  onSubmit: (data: SurveyData) => void;
  onCancel: () => void;
  studentCode?: string; // Code generated by Excel
}

export const SurveyForm: React.FC<SurveyFormProps> = ({ onSubmit, onCancel, studentCode }) => {
  const [formData, setFormData] = useState<SurveyData>({
    completed: true,
    destination: '',
    transportMethod: 'PARENT_CAR',
    healthStatus: 'GOOD',
    comments: ''
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.destination) {
      alert("Por favor indica tu destino.");
      return;
    }
    onSubmit({
      ...formData,
      submittedAt: new Date().toISOString()
    });
  };

  const openGoogleForm = () => {
    // Uses the Base URL from constants and appends the student code as a pre-filled entry
    // Note: 'entry.123456' is a placeholder. You must replace it with the actual Field ID from your Google Form.
    // Example: https://docs.google.com/forms/d/e/.../viewform?usp=pp_url&entry.109283=COAR-ANA5678
    const codeParam = `?usp=pp_url&entry.123456=${studentCode || 'COAR-XXXX'}`; 
    window.open(GOOGLE_FORM_BASE_URL + codeParam, '_blank');
  };

  return (
    <div className="flex-1 flex flex-col bg-gray-50 h-full overflow-y-auto">
      <div className="bg-gradient-to-r from-purple-600 to-indigo-600 p-6 rounded-b-3xl shadow-lg">
        <div className="flex items-center justify-between text-white mb-2">
           <h2 className="font-bold text-xl">Encuesta de Salida</h2>
           <Icons.Survey className="w-6 h-6 opacity-80" />
        </div>
        <p className="text-indigo-100 text-xs">Miércoles de Integración Familiar</p>
      </div>

      <div className="p-4 mx-6 mt-4 bg-yellow-50 border border-yellow-200 rounded-xl flex items-start gap-3">
         <div className="bg-yellow-100 p-2 rounded-full text-yellow-700 mt-1">
            <Icons.Layers className="w-4 h-4" />
         </div>
         <div>
            <p className="text-xs text-yellow-800 font-bold">¿Prefieres el formulario clásico?</p>
            <p className="text-[10px] text-yellow-700 mb-2">Si tienes problemas con la app, puedes usar el Google Form oficial.</p>
            <button 
              onClick={openGoogleForm}
              className="text-[10px] font-bold text-yellow-800 underline hover:text-yellow-600"
            >
              Abrir Google Form externo (Código: {studentCode})
            </button>
         </div>
      </div>

      <form onSubmit={handleSubmit} className="p-6 space-y-6">
        
        {/* Destination */}
        <div className="space-y-2">
           <label className="text-sm font-bold text-gray-700 flex items-center">
             <Icons.MapPin className="w-4 h-4 mr-2 text-indigo-600" />
             ¿Hacia dónde te diriges hoy?
           </label>
           <input 
             type="text"
             value={formData.destination}
             onChange={(e) => setFormData({...formData, destination: e.target.value})}
             placeholder="Ej: Casa en Juliaca, Centro de Puno..."
             className="w-full p-4 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none"
             required
           />
        </div>

        {/* Transport */}
        <div className="space-y-2">
           <label className="text-sm font-bold text-gray-700 flex items-center">
             <Icons.Car className="w-4 h-4 mr-2 text-indigo-600" />
             Medio de Transporte
           </label>
           <div className="grid grid-cols-2 gap-3">
              <button
                type="button"
                onClick={() => setFormData({...formData, transportMethod: 'PARENT_CAR'})}
                className={`p-3 rounded-xl border-2 text-xs font-bold transition-all ${formData.transportMethod === 'PARENT_CAR' ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-gray-100 bg-white text-gray-500'}`}
              >
                Vehículo Familiar
              </button>
              <button
                type="button"
                onClick={() => setFormData({...formData, transportMethod: 'BUS'})}
                className={`p-3 rounded-xl border-2 text-xs font-bold transition-all ${formData.transportMethod === 'BUS' ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-gray-100 bg-white text-gray-500'}`}
              >
                Transporte Público
              </button>
              <button
                type="button"
                onClick={() => setFormData({...formData, transportMethod: 'WALK'})}
                className={`p-3 rounded-xl border-2 text-xs font-bold transition-all ${formData.transportMethod === 'WALK' ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-gray-100 bg-white text-gray-500'}`}
              >
                A pie
              </button>
              <button
                type="button"
                onClick={() => setFormData({...formData, transportMethod: 'OTHER'})}
                className={`p-3 rounded-xl border-2 text-xs font-bold transition-all ${formData.transportMethod === 'OTHER' ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-gray-100 bg-white text-gray-500'}`}
              >
                Otro
              </button>
           </div>
        </div>

        {/* Health */}
        <div className="space-y-2">
           <label className="text-sm font-bold text-gray-700 flex items-center">
             <Icons.Shield className="w-4 h-4 mr-2 text-indigo-600" />
             Estado de Salud
           </label>
           <div className="flex gap-3">
             <button
                type="button"
                onClick={() => setFormData({...formData, healthStatus: 'GOOD'})}
                className={`flex-1 p-4 rounded-xl border-2 text-sm font-bold transition-all flex items-center justify-center gap-2 ${formData.healthStatus === 'GOOD' ? 'border-green-500 bg-green-50 text-green-700' : 'border-gray-100 bg-white text-gray-400'}`}
              >
                <Icons.Check className="w-4 h-4" /> Me siento bien
              </button>
              <button
                type="button"
                onClick={() => setFormData({...formData, healthStatus: 'SICK'})}
                className={`flex-1 p-4 rounded-xl border-2 text-sm font-bold transition-all flex items-center justify-center gap-2 ${formData.healthStatus === 'SICK' ? 'border-red-500 bg-red-50 text-red-700' : 'border-gray-100 bg-white text-gray-400'}`}
              >
                <Icons.Close className="w-4 h-4" /> Tengo malestar
              </button>
           </div>
        </div>

        {/* Comments */}
        <div className="space-y-2">
           <label className="text-sm font-bold text-gray-700">Comentarios adicionales</label>
           <textarea 
             value={formData.comments}
             onChange={(e) => setFormData({...formData, comments: e.target.value})}
             className="w-full p-3 rounded-xl border border-gray-200 text-sm focus:ring-2 focus:ring-indigo-500 outline-none h-24 resize-none"
             placeholder="¿Alguna nota para tu tutor?"
           />
        </div>

        <div className="pt-4 flex gap-3">
           <button 
             type="button" 
             onClick={onCancel}
             className="flex-1 py-4 rounded-xl text-gray-500 font-bold hover:bg-gray-100 transition-colors"
           >
             Cancelar
           </button>
           <button 
             type="submit"
             className="flex-[2] py-4 rounded-xl bg-indigo-600 text-white font-bold shadow-lg shadow-indigo-200 hover:bg-indigo-700 transition-all active:scale-95"
           >
             Enviar Encuesta
           </button>
        </div>

      </form>
    </div>
  );
};
